version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=secret
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_NAME: postgres
