version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=secret
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    volumes:
      - ./docker/server:/usr/src/app/docker/server:delegated
      - ./app:/usr/src/app/app:delegated
      - ./notifications:/usr/src/app/notifications:delegated
      - ./pact:/usr/src/app/pact:delegated
      - ./manage.py:/usr/src/app/manage.py:delegated
    ports:
      - '8000:8000'
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_NAME: postgres
