# Generated by Django 2.2.9 on 2020-01-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification", old_name="subscribers", new_name="subscriber",
        ),
    ]
