# Generated by Django 2.2.9 on 2020-01-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_auto_20200130_1638"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Subscriber",),
        migrations.RenameField(
            model_name="subscriber", old_name="user_id", new_name="subscriber_id",
        ),
    ]
