name: Docker
on:
  pull_request:
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -f docker/server/Dockerfile -t notifications:latest .
