name: Docker
on:
  pull_request:
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build --file docker/server/Dockerfile --tag notifications-server .
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build --file docker/worker/Dockerfile --tag notifications-worker .
