name: Docker
on:
  pull_request:
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -f docker/server/Dockerfile -t serlo-org-notifications:latest .
